# Generated by Django 3.1.7 on 2021-04-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210406_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
