# Generated by Django 3.1.7 on 2021-04-12 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
    ]
